# Specify analysis options.
#
# For the default rule set, see:
# https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "bin/cache/**"
    - build/**
    - android/**
    - ios/**
    - web/**
