name: build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ...
    steps:
    # ~ビルドのステップは省略~
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
